version: "3.4"

services:
  api:
    image: "containerregistrydariamiu30442.azurecr.io/backend-image-a2:latest"
    domainname: "backend-a2"
    ports:
      - 8080:8080
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      DB_IP: demo-db
      RABBIT_IP: demo-rabbit
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: cara12345
      DB_DBNAME: energy_utility_platform
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 2G

  db:
    image: "containerregistrydariamiu30442.azurecr.io/db:latest"
    environment:
      MYSQL_DATABASE: energy_utility_platform
      MYSQL_ROOT_PASSWORD: cara12345
      MYSQL_HOST_AUTH_METHOD: trust
    domainname: "backend-a2"
    ports:
      - 3307:3306
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 2G
  rabbitmq:
    image: "containerregistrydariamiu30442.azurecr.io/rabbitmq:latest"
    domainname: "backend-a2"
    ports:
      - 15672:15672
      - 5672:5672
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 2G
