version: '3'

services:

  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=energy_utility_platform
      - MYSQL_ROOT_PASSWORD=cara12345
      - MYSQL_HOST_AUTH_METHOD=trust
    ports:
      - "3307:3306"
    container_name: database-a2

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    image: backend-image-a2
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - DB_IP=demo-db
      - RABBIT_IP=demo-rabbit
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=cara12345
      - DB_DBNAME=energy_utility_platform
    depends_on:
      - rabbitmq
      - database
      -

